#!/bin/bash

echo "🚀 Quick Deployment Setup for Render + Netlify"
echo "=============================================="

# Check if git is initialized
if [ ! -d ".git" ]; then
    echo "📁 Initializing git repository..."
    git init
    git add .
    git commit -m "Initial commit for deployment"
    echo "⚠️  Please add your GitHub repository as remote origin:"
    echo "   git remote add origin https://github.com/yourusername/your-repo-name.git"
    echo "   git push -u origin main"
fi

echo ""
echo "✅ Your project is ready for deployment!"
echo ""
echo "📋 Deployment Steps:"
echo ""
echo "🔧 STEP 1: MongoDB Atlas Setup"
echo "   1. Follow MONGODB_SETUP.md instructions"
echo "   2. Get your connection string"
echo "   3. Generate a JWT secret:"
echo "      node -e \"console.log(require('crypto').randomBytes(64).toString('hex'))\""
echo ""
echo "🖥️ STEP 2: Deploy Backend to Render"
echo "   1. Go to https://render.com"
echo "   2. Sign up with GitHub"
echo "   3. Click 'New +' → 'Web Service'"
echo "   4. Connect your GitHub repository"
echo "   5. Configure:"
echo "      - Name: linkedin-clone-backend"
echo "      - Build Command: cd server && npm install"
echo "      - Start Command: cd server && node server.js"
echo "   6. Add environment variables:"
echo "      - NODE_ENV=production"
echo "      - MONGODB_URI=your-mongodb-connection-string"
echo "      - JWT_SECRET=your-jwt-secret"
echo "      - PORT=10000"
echo ""
echo "🌐 STEP 3: Deploy Frontend to Netlify"
echo "   1. Go to https://netlify.com"
echo "   2. Sign up with GitHub"
echo "   3. Click 'New site from Git'"
echo "   4. Choose your repository"
echo "   5. Configure:"
echo "      - Build command: npm run build"
echo "      - Publish directory: dist"
echo "   6. Add environment variable:"
echo "      - VITE_API_URL=https://your-backend-name.onrender.com/api"
echo ""
echo "🔗 STEP 4: Update CORS"
echo "   1. Get your Netlify domain"
echo "   2. Update server/server.js CORS origin"
echo "   3. Redeploy backend"
echo ""
echo "🎉 Your app will be live at:"
echo "   Frontend: https://your-app-name.netlify.app"
echo "   Backend: https://your-backend-name.onrender.com"
echo ""
echo "📚 For detailed instructions, see DEPLOYMENT-NETLIFY-RENDER.md" 